### PR TITLE
javamail API not working in Android - issue fixed

### PR DESCRIPTION
**Pull request by sathyapriya31**
@sambhav2612 Added strict mode to handle NetworkOnMainThreadException #1

### CODE REVIEW

**Comment by sambhav2612** [comment]
@sathyapriya31 is it working? Have you tried this on your device/emulator? If yes, than please let me know what I was missing earlier. I'll merge if it's working though.

**Comment by sathyapriya31** [comment]
@sambhav2612 i tested on device its working fine. please enable less secure app aceess your account

**Review by sambhav2612 — APPROVED** [review]

**Comment by sambhav2612** [comment]
Great! Then I'm approving this and merging it. Thanks for the help!

**Comment by sambhav2612** [comment]
It didn't work @sathyapriya31

**Comment by sathyapriya31** [comment]
@sambhav2612 i checked with my email id. its working fine. Did you enable less secure app access your account
screenshot_20171026-120601

**Comment by sambhav2612** [comment]
Yes, it is enabled

**Pull request merged**
